### ISSUE TITLE
Conflicting Mujoco dependencies for Adroit?

### ISSUE THREAD

**Issue by StoneT2000** [ikostrikov/rlpd#1]
It seems the gym version required uses Mujoco 150 or something, but the sparse adroit envs use a later version when installed. Any idea which should be used?

**Comment by StoneT2000** [comment]
It seems mujoco 150 works for the D4RL locomotion and AdroitSparse, but unsure how this may impact reproducibility.

**Comment by philipjball** [comment]
This rings a bell; I believe if you precisely follow the installation instructions, it should reproduce the results, even if it throws conflicts. Regarding compared to other papers, I've personally not found a difference in MJC version, but happy to look into this if there is a repro problem.
