### ISSUE TITLE
Reproducing normalized scores on door-binary

### ISSUE THREAD

**Issue by StoneT2000** [ikostrikov/rlpd#3]
Currently we are trying to recreate the door-binary results but it seems either the performance is not as good as the results or we compute the normalized score wrong.

![image](https://github.com/ikostrikov/rlpd/assets/35373228/4cda4182-c8df-4f8a-b159-04775bb2cb40)
After running the example script for door-binary (the pen-binary one but changed the env name), it seems the eval return goes only as high as around -33, which to my understanding is equivalent to taking 33 steps to reach a success state / receive reward 0 instead of reward -1. 

However, the paper shows a training curve where the normalized score reaches around 80, which should be equivalent to a eval return on door-binary of around -20? 

Any help on understanding how normalized scores are computed / this discrepancy is much appreciated!

**Comment by philipjball** [comment]
I think this is actually correct; bear in mind that the door environment has a horizon of 200 (whereas pen is 100)! So basically if you halve everything, you seem to get a score of around 80, which I believe matches the paper? Let me know if this makes sense 😄

**Comment by StoneT2000** [comment]
Sorry this doesn't quite make sense?

I believe the reward function is -1 if not success state, and 0 if it's a success states

In that case, if the horizon is even 1000 steps, i should expect the same total return if the horizon is 100 steps as in both cases the agent completes the task in the same amount of time, accumulating the same number of -1 reward before getting 0 for the rest of the episode.

Let me know if that helps explain my confusion?

And thanks for responding to all the other issues!

**Comment by philipjball** [comment]
Recall that we normalize w.r.t. the horizon so that all values fall between 0 and 100. In this case with T=1000, let's say you solved the task in 900 steps; this means getting a normalized score of 10 (not -800), since you only resided in a "success" state for 10% of the duration of the experiment. I hope this makes sense!

**Comment by StoneT2000** [comment]
ah ok I misunderstood, I thought the paper used absolute value not percent. Thank you this clears it up

**Comment by philipjball** [comment]
No problem, I'd just like to add for future reference/readers that this is the same evaluation methodology for these domains as was performed in [prior](https://arxiv.org/abs/2110.06169) and [concurrent](https://arxiv.org/abs/2204.02372) work.
